name: Scorecard supply-chain security

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6:00 AM UTC
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to scan'
        required: true
        default: 'notebooks-v2'
        type: choice
        options:
          - notebooks-v1
          - notebooks-v2

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    if: github.event_name == 'workflow_dispatch' || ( github.event_name == 'schedule' && github.repository == 'kubeflow/notebooks' )
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write   # Needed to upload the results to code-scanning dashboard.
      id-token: write          # Needed to publish results and get a badge (see publish_results below).
    strategy:
      matrix:
        branch: ${{ github.event_name == 'workflow_dispatch' && fromJSON(format('["{0}"]', github.event.inputs.branch)) || fromJSON('["notebooks-v1", "notebooks-v2"]') }}

    steps:
      - name: "Checkout code"
        id: checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  #v4.3.0
        with:
          persist-credentials: false
          ref: refs/heads/${{ matrix.branch }}

      - name: "Run Scorecard analysis"
        uses: ossf/scorecard-action@05b42c624433fc40578a4040d5cf5e36ddca8cde # v2.4.2
        with:
          results_file: scorecard-fs-scan-results-${{ matrix.branch }}.sarif
          results_format: sarif
          source: local 
          publish_results: false

      # - name: Add branch metadata to SARIF
      #   run: |
      #     # Modify ruleId to include branch information for identification
      #     jq '.runs[0].results[] |= (.ruleId = "scorecard/${{ matrix.branch }}/" + .ruleId)' \
      #       scorecard-fs-scan-results-${{ matrix.branch }}.sarif > scorecard-fs-scan-results-${{ matrix.branch }}-processed.sarif
      #     mv scorecard-fs-scan-results-${{ matrix.branch }}-processed.sarif scorecard-fs-scan-results-${{ matrix.branch }}.sarif

      - name: "Upload Scorecard results as artifact"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: scorecard-fs-scan-results-${{ matrix.branch }}
          path: scorecard-fs-scan-results-${{ matrix.branch }}.sarif
          retention-days: 5

      - name: "Upload scorecard results to GitHub's code scanning dashboard"
        uses: github/codeql-action/upload-sarif@181d5eefc20863364f96762470ba6f862bdef56b # v3.29.2
        with:
          sarif_file: 'scorecard-fs-scan-results-${{ matrix.branch }}.sarif'
          ref: ${{ steps.checkout.outputs.ref }}
          sha: ${{ steps.checkout.outputs.commit }}
